version: "3.8"


services:

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_turismo_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: resende123

  turismo-api:
    build:
      context: https://github.com/dmarck82/turismo-api.git
    ports:
      - 8095:8080
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_turismo_api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: resende123  
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      
  turismo-api-2:
    build:
      context: https://github.com/dmarck82/turismo-api-2.git
    ports:
      - 8096:3001

  turismo-front:
    build:
      context: https://github.com/dmarck82/turismo-front.git
    ports:
      - 8097:3000
    environment:
      - REACT_APP_API1_URL=http://turismo-api:8080
      - REACT_APP_API2_URL=http://turismo-api-2:3001
    depends_on:
      - turismo-api
      - turismo-api-2

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - turismo-front
      - turismo-api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: always
    privileged: true
    user: root
    tty: true
    stdin_open: true
    ports:
      - 8090:8080
      - 50000:50000
    container_name: "jenkins"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker


volumes:
  jenkins_home: